import { useMemo } from 'react';
import type { Claim } from '@/types/claim';

const SAMPLE_CLAIMS: Claim[] = [
  {
    id: 'CLM-1001',
    date: '2026-04-10',
    reg: 'AB12 CDE',
    customerName: 'John Smith',
    email: 'john.smith@example.com',
    phone: '07700 900111',
    issue: 'Engine warning light, loss of power',
    ageInDays: 16,
    status: 'overdue',
    priority: 'critical',
    assignee: 'unassigned',
    amount: 1850,
    evidence: 'Missing',
  },
  {
    id: 'CLM-1002',
    date: '2026-04-12',
    reg: 'BD63 FGH',
    customerName: 'Sarah Johnson',
    email: 'sarah.j@example.com',
    phone: '07700 900222',
    issue: 'Gearbox failure on motorway',
    ageInDays: 14,
    status: 'overdue',
    priority: 'critical',
    assignee: 'unassigned',
    amount: 3200,
    evidence: 'Partial',
  },
  {
    id: 'CLM-1003',
    date: '2026-04-15',
    reg: 'LM15 NOP',
    customerName: 'David Williams',
    email: 'd.williams@example.com',
    phone: '07700 900333',
    issue: 'Air conditioning not working',
    ageInDays: 11,
    status: 'overdue',
    priority: 'high',
    assignee: 'Emma Clark',
    amount: 450,
    evidence: 'Received',
  },
  {
    id: 'CLM-1004',
    date: '2026-04-18',
    reg: 'PQ17 RST',
    customerName: 'Rachel Brown',
    email: 'rachel.b@example.com',
    phone: '07700 900444',
    issue: 'Suspension noise on bumps',
    ageInDays: 8,
    status: 'evidence',
    priority: 'high',
    assignee: 'Tom Wilson',
    amount: 720,
    evidence: 'Partial',
  },
  {
    id: 'CLM-1005',
    date: '2026-04-19',
    reg: 'UV19 WXY',
    customerName: 'Michael Davis',
    email: 'mdavis@example.com',
    phone: '07700 900555',
    issue: 'Brake pedal soft, ABS warning',
    ageInDays: 7,
    status: 'evidence',
    priority: 'high',
    assignee: 'Emma Clark',
    amount: 540,
    evidence: 'Missing',
  },
  {
    id: 'CLM-1006',
    date: '2026-04-21',
    reg: 'ZA20 BCD',
    customerName: 'Laura Taylor',
    email: 'l.taylor@example.com',
    phone: '07700 900666',
    issue: 'Alternator replacement required',
    ageInDays: 5,
    status: 'review',
    priority: 'normal',
    assignee: 'Tom Wilson',
    amount: 380,
    evidence: 'Received',
  },
  {
    id: 'CLM-1007',
    date: '2026-04-22',
    reg: 'EF21 GHI',
    customerName: 'James Miller',
    email: 'jmiller@example.com',
    phone: '07700 900777',
    issue: 'Turbocharger failure',
    ageInDays: 4,
    status: 'review',
    priority: 'normal',
    assignee: 'Emma Clark',
    amount: 1650,
    evidence: 'Received',
  },
  {
    id: 'CLM-1008',
    date: '2026-04-23',
    reg: 'JK22 LMN',
    customerName: 'Sophie Anderson',
    email: 'sophie.a@example.com',
    phone: '07700 900888',
    issue: 'Clutch slipping under load',
    ageInDays: 3,
    status: 'approved',
    priority: 'normal',
    assignee: 'Tom Wilson',
    amount: 890,
    evidence: 'Received',
  },
  {
    id: 'CLM-1009',
    date: '2026-04-24',
    reg: 'OP23 QRS',
    customerName: 'Daniel Thomas',
    email: 'd.thomas@example.com',
    phone: '07700 900999',
    issue: 'Power steering pump leak',
    ageInDays: 2,
    status: 'open',
    priority: 'low',
    assignee: 'Emma Clark',
    amount: 410,
    evidence: 'Partial',
  },
  {
    id: 'CLM-1010',
    date: '2026-04-25',
    reg: 'TU24 VWX',
    customerName: 'Olivia Martin',
    email: 'olivia.m@example.com',
    phone: '07700 900100',
    issue: 'Window regulator broken',
    ageInDays: 1,
    status: 'closed',
    priority: 'low',
    assignee: 'Tom Wilson',
    amount: 220,
    evidence: 'Received',
  },
];

export function useClaims() {
  const claims = useMemo<Claim[]>(() => SAMPLE_CLAIMS, []);
  return { claims, count: claims.length };
}
