insert into public.abandoned_cart_email_templates (trigger_type, name, subject, html_content, is_active, send_delay_minutes)
values
  ('nurture_14d','Nurture day 14','Your warranty quote is still here','Generated by send-abandoned-cart-email',true,20160),
  ('nurture_30d','Nurture day 30','What a warranty covers (and what it saves)','Generated by send-abandoned-cart-email',true,43200),
  ('nurture_60d','Nurture month 2','Cover from around 60p a day','Generated by send-abandoned-cart-email',true,86400),
  ('nurture_90d','Nurture month 3','Is your car still unprotected?','Generated by send-abandoned-cart-email',true,129600),
  ('nurture_120d','Nurture month 4','A fresh warranty price for you','Generated by send-abandoned-cart-email',true,172800),
  ('nurture_150d','Nurture month 5','Peace of mind for your car','Generated by send-abandoned-cart-email',true,216000),
  ('nurture_180d','Nurture month 6','Last email about your quote','Generated by send-abandoned-cart-email',true,259200)
on conflict do nothing;