// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { queuedFetch } from '@/lib/requestQueue';

const SUPABASE_URL = "https://mzlpuxzwyrcyrgrongeb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16bHB1eHp3eXJjeXJncm9uZ2ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4ODc0MjUsImV4cCI6MjA2NjQ2MzQyNX0.bFu0Zj4ic61GN0LwipkINg9YJtgd8RnMgEmzE139MPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/**
 * TRUE SINGLETON.
 *
 * Two things used to be able to create a second auth client in the same tab:
 * a Vite HMR reload of this module, and any lazily-loaded bundle importing a
 * fresh copy of it. Two GoTrueClients on the same storage key fight over the
 * refresh token ("Multiple GoTrueClient instances detected") and can wipe the
 * session — which reads as a frozen/blank screen. Caching the instance on
 * globalThis guarantees one client per browser tab.
 *
 * Cross-tab safety: `storageKey` is explicit and auth-js uses the Web Locks API
 * (navigator.locks) by default in the browser, so when an agent has 4 CRM tabs
 * open only ONE of them refreshes the token and the others read the rotated
 * session from storage instead of racing it.
 */
const GLOBAL_KEY = '__baw_supabase_client__';
const g = globalThis as typeof globalThis & {
  [GLOBAL_KEY]?: SupabaseClient<Database>;
};

export const supabase: SupabaseClient<Database> =
  g[GLOBAL_KEY] ??
  createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? window.localStorage : undefined,
      storageKey: 'sb-mzlpuxzwyrcyrgrongeb-auth-token',
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
    },
    // All data requests are paced through a global concurrency limiter so the
    // dashboard can never overflow the browser's socket queue
    // (net::ERR_INSUFFICIENT_RESOURCES). Auth/realtime bypass it.
    global: { fetch: queuedFetch },
    realtime: {
      // One tab never needs more than a trickle of realtime events per second;
      // this stops a burst on a busy table from pegging the CPU in every tab.
      params: { eventsPerSecond: 5 },
    },
  });

g[GLOBAL_KEY] = supabase;
